export type LayerCategory = 
  | "ADMINISTRATIVE"
  | "URBAN"
  | "FOREST"
  | "LAND_OWNERSHIP"
  | "TRANSPORT"
  | "EDUCATION"
  | "PUBLIC_UTILITIES"
  | "GOVERNMENT_FACILITIES"
  | "WATER"
  | "NATURAL_RESOURCES"
  | "LAND_USE"
  | "INFRASTRUCTURE"
  | "ENVIRONMENT"
  | "DEPARTMENTAL";

export type GeometryType = "Point" | "LineString" | "Polygon" | "MultiPoint" | "MultiLineString" | "MultiPolygon" | "Raster";

export type SourceType = "POSTGIS" | "WMS" | "WFS" | "VECTOR_TILE" | "GEOJSON";

export type DataStatus = "OFFICIAL" | "OFFICIAL_API" | "OFFICIAL_REFERENCE" | "USER_UPLOADED" | "PENDING_VERIFICATION";

export interface LayerMetadata {
  id: string;
  name: string;
  category: LayerCategory;
  geometry_type: GeometryType;
  source: string; // API endpoint or table name or WMS URL
  source_type: SourceType;
  visibility: boolean; // default visibility
  min_zoom: number;
  max_zoom: number;
  selectable: boolean;
  queryable: boolean;
  downloadable: boolean;
  searchable: boolean;
  style: {
    color?: string;
    fillColor?: string;
    weight?: number;
    opacity?: number;
    fillOpacity?: number;
    icon?: string;
    dashArray?: string;
  };
  attribution: string;
  update_frequency: string;
  data_status: DataStatus;
  source_department: string;
  source_system?: string;
  source_url?: string;
  last_verified?: string;
  license_or_usage_status?: string;
}

export const GIS_LAYER_REGISTRY: LayerMetadata[] = [
  // ==========================
  // ADMINISTRATIVE
  // ==========================
  {
    id: "states",
    name: "State Boundary",
    category: "ADMINISTRATIVE",
    geometry_type: "MultiPolygon",
    source: "/api/v1/gis/layer/states",
    source_type: "POSTGIS",
    visibility: false,
    min_zoom: 1,
    max_zoom: 19,
    selectable: true,
    queryable: true,
    downloadable: false,
    searchable: true,
    style: { color: "#4f46e5", fillColor: "transparent", weight: 3 },
    attribution: "TNGIS Official Source",
    update_frequency: "Yearly",
    data_status: "OFFICIAL_API",
    source_department: "TNeGA / TNGIS",
  },
  {
    id: "districts",
    name: "Districts",
    category: "ADMINISTRATIVE",
    geometry_type: "MultiPolygon",
    source: "/api/v1/gis/layer/districts",
    source_type: "POSTGIS",
    visibility: false,
    min_zoom: 6,
    max_zoom: 19,
    selectable: true,
    queryable: true,
    downloadable: false,
    searchable: true,
    style: { color: "#6366f1", fillColor: "#818cf8", weight: 2, fillOpacity: 0.1 },
    attribution: "TNGIS Official Source",
    update_frequency: "Yearly",
    data_status: "OFFICIAL_API",
    source_department: "TNeGA / TNGIS",
  },
  {
    id: "taluks",
    name: "Taluks",
    category: "ADMINISTRATIVE",
    geometry_type: "MultiPolygon",
    source: "/api/v1/gis/layer/taluks",
    source_type: "POSTGIS",
    visibility: false,
    min_zoom: 9,
    max_zoom: 19,
    selectable: true,
    queryable: true,
    downloadable: false,
    searchable: true,
    style: { color: "#8b5cf6", fillColor: "#a78bfa", weight: 2, fillOpacity: 0.1 },
    attribution: "TNGIS Official Source",
    update_frequency: "Yearly",
    data_status: "OFFICIAL_API",
    source_department: "TNeGA / TNGIS",
  },
  {
    id: "villages",
    name: "Revenue Villages",
    category: "ADMINISTRATIVE",
    geometry_type: "MultiPolygon",
    source: "/api/v1/gis/layer/villages",
    source_type: "POSTGIS",
    visibility: false,
    min_zoom: 11,
    max_zoom: 19,
    selectable: true,
    queryable: true,
    downloadable: false,
    searchable: true,
    style: { color: "#d946ef", fillColor: "transparent", weight: 1, fillOpacity: 0 },
    attribution: "TNGIS Official Source",
    update_frequency: "Yearly",
    data_status: "OFFICIAL_API",
    source_department: "TNeGA / TNGIS",
  },

  // ==========================
  // NATURAL RESOURCES
  // ==========================
  {
    id: "geology",
    name: "Geology",
    category: "NATURAL_RESOURCES",
    geometry_type: "MultiPolygon",
    source: "/api/v1/gis/layer/geology",
    source_type: "POSTGIS",
    visibility: false,
    min_zoom: 10,
    max_zoom: 19,
    selectable: true,
    queryable: true,
    downloadable: true,
    searchable: false,
    style: { color: "#059669", fillColor: "#10b981", weight: 2, fillOpacity: 0.2 },
    attribution: "Geological Survey of India via TNGIS",
    update_frequency: "Decade",
    data_status: "OFFICIAL_API",
    source_department: "GSI",
  },
  {
    id: "soil",
    name: "Soil Classification",
    category: "NATURAL_RESOURCES",
    geometry_type: "MultiPolygon",
    source: "/api/v1/gis/layer/soil",
    source_type: "POSTGIS",
    visibility: false,
    min_zoom: 10,
    max_zoom: 19,
    selectable: true,
    queryable: true,
    downloadable: true,
    searchable: false,
    style: { color: "#d97706", fillColor: "#f59e0b", weight: 2, fillOpacity: 0.2 },
    attribution: "Agriculture Department via TNGIS",
    update_frequency: "Decade",
    data_status: "OFFICIAL_API",
    source_department: "Agriculture",
  },

  // ==========================
  // LAND USE
  // ==========================
  {
    id: "landuse",
    name: "Land Use (LULC)",
    category: "LAND_USE",
    geometry_type: "MultiPolygon",
    source: "/api/v1/gis/layer/landuse",
    source_type: "POSTGIS",
    visibility: false,
    min_zoom: 12,
    max_zoom: 19,
    selectable: true,
    queryable: true,
    downloadable: false,
    searchable: true,
    style: { color: "#2563eb", fillColor: "#3b82f6", weight: 1, fillOpacity: 0.3 },
    attribution: "DTCP / CMDA via TNGIS",
    update_frequency: "5 Years",
    data_status: "OFFICIAL_API",
    source_department: "Urban Planning",
  },

  // ==========================
  // WATER BODIES
  // ==========================
  {
    id: "waterbodies",
    name: "Rivers & Lakes",
    category: "WATER",
    geometry_type: "MultiPolygon",
    source: "/api/v1/gis/layer/waterbodies",
    source_type: "POSTGIS",
    visibility: false,
    min_zoom: 10,
    max_zoom: 19,
    selectable: true,
    queryable: true,
    downloadable: false,
    searchable: true,
    style: { color: "#0284c7", fillColor: "#38bdf8", weight: 2, fillOpacity: 0.4 },
    attribution: "Water Resources Dept via TNGIS",
    update_frequency: "Yearly",
    data_status: "OFFICIAL_API",
    source_department: "PWD",
  },

  // ==========================
  // TRANSPORT
  // ==========================
  {
    id: "roads",
    name: "Road Network",
    category: "TRANSPORT",
    geometry_type: "MultiLineString",
    source: "/api/v1/gis/layer/roads",
    source_type: "POSTGIS",
    visibility: false,
    min_zoom: 12,
    max_zoom: 19,
    selectable: true,
    queryable: true,
    downloadable: false,
    searchable: true,
    style: { color: "#6b7280", weight: 3 },
    attribution: "Highways Department via TNGIS",
    update_frequency: "Yearly",
    data_status: "OFFICIAL_API",
    source_department: "Highways",
  },

  // ==========================
  // ENVIRONMENT / RISK
  // ==========================
  {
    id: "risk_zones",
    name: "Hazard / Risk Zones",
    category: "ENVIRONMENT",
    geometry_type: "MultiPolygon",
    source: "/api/v1/gis/layer/risk_zones",
    source_type: "POSTGIS",
    visibility: false,
    min_zoom: 10,
    max_zoom: 19,
    selectable: true,
    queryable: true,
    downloadable: false,
    searchable: true,
    style: { color: "#dc2626", fillColor: "#ef4444", weight: 2, fillOpacity: 0.2 },
    attribution: "Disaster Management via TNGIS",
    update_frequency: "Yearly",
    data_status: "OFFICIAL_API",
    source_department: "SDMA",
  },

  // ==========================
  // FOREST
  // ==========================
  {
    id: "forest_reserve",
    name: "Reserve Forest",
    category: "FOREST",
    geometry_type: "MultiPolygon",
    source: "/api/v1/gis/layer/forest_reserve",
    source_type: "POSTGIS",
    visibility: false,
    min_zoom: 8,
    max_zoom: 19,
    selectable: false,
    queryable: false,
    downloadable: false,
    searchable: false,
    style: { color: "#14532d", fillColor: "#166534", weight: 2, fillOpacity: 0.3 },
    attribution: "Forest Department via TNGIS",
    update_frequency: "Yearly",
    data_status: "OFFICIAL_API",
    source_department: "Forest Department",
  },

  // ==========================
  // LAND OWNERSHIP
  // ==========================
  {
    id: "cadastral_parcels",
    name: "Cadastral Survey Boundaries",
    category: "LAND_OWNERSHIP",
    geometry_type: "Polygon",
    source: "/api/v1/gis/layer/cadastral_parcels",
    source_type: "WFS",
    visibility: false,
    min_zoom: 8,
    max_zoom: 22,
    selectable: true,
    queryable: true,
    downloadable: false,
    searchable: true,
    style: { color: "#d97706", fillColor: "#f59e0b", weight: 2, fillOpacity: 0.25 },
    attribution: "Survey and Settlement Dept — LAND STACK",
    update_frequency: "Daily",
    data_status: "OFFICIAL",
    source_department: "Survey and Settlement",
  },
  
  // ==========================
  // EDUCATION
  // ==========================
  {
    id: "schools",
    name: "Schools",
    category: "EDUCATION",
    geometry_type: "Point",
    source: "/api/v1/gis/layer/schools",
    source_type: "POSTGIS",
    visibility: false,
    min_zoom: 14,
    max_zoom: 22,
    selectable: true,
    queryable: true,
    downloadable: false,
    searchable: true,
    style: { icon: "🏫" },
    attribution: "School Education via TNGIS",
    update_frequency: "Yearly",
    data_status: "OFFICIAL_API",
    source_department: "School Education",
  },
  
  // ==========================
  // ADDED FOR PHASE 9 (MISSING 17)
  // ==========================
  {
    id: "panchayat_villages",
    name: "Panchayat Village Boundary",
    category: "ADMINISTRATIVE",
    geometry_type: "MultiPolygon",
    source: "/api/v1/gis/layer/panchayat_villages",
    source_type: "POSTGIS",
    visibility: false,
    min_zoom: 11,
    max_zoom: 19,
    selectable: true,
    queryable: true,
    downloadable: false,
    searchable: true,
    style: { color: "#d946ef", fillColor: "transparent", weight: 1, fillOpacity: 0 },
    attribution: "TNGIS Official Source",
    update_frequency: "Yearly",
    data_status: "PENDING_VERIFICATION",
    source_department: "TNeGA / Rural Development",
  },
  {
    id: "blocks",
    name: "Blocks",
    category: "ADMINISTRATIVE",
    geometry_type: "MultiPolygon",
    source: "/api/v1/gis/layer/blocks",
    source_type: "POSTGIS",
    visibility: false,
    min_zoom: 9,
    max_zoom: 19,
    selectable: true,
    queryable: true,
    downloadable: false,
    searchable: true,
    style: { color: "#8b5cf6", fillColor: "transparent", weight: 2, fillOpacity: 0 },
    attribution: "TNGIS Official Source",
    update_frequency: "Yearly",
    data_status: "PENDING_VERIFICATION",
    source_department: "TNeGA",
  },
  {
    id: "national_highways",
    name: "National Highways",
    category: "TRANSPORT",
    geometry_type: "MultiLineString",
    source: "/api/v1/gis/layer/national_highways",
    source_type: "POSTGIS",
    visibility: false,
    min_zoom: 5,
    max_zoom: 19,
    selectable: true,
    queryable: true,
    downloadable: false,
    searchable: true,
    style: { color: "#fbbf24", weight: 4 },
    attribution: "TNGIS Official Source",
    update_frequency: "Yearly",
    data_status: "PENDING_VERIFICATION",
    source_department: "Highways",
  },
  {
    id: "state_highways",
    name: "State Highways",
    category: "TRANSPORT",
    geometry_type: "MultiLineString",
    source: "/api/v1/gis/layer/state_highways",
    source_type: "POSTGIS",
    visibility: false,
    min_zoom: 7,
    max_zoom: 19,
    selectable: true,
    queryable: true,
    downloadable: false,
    searchable: true,
    style: { color: "#f59e0b", weight: 3 },
    attribution: "TNGIS Official Source",
    update_frequency: "Yearly",
    data_status: "PENDING_VERIFICATION",
    source_department: "Highways",
  },
  {
    id: "major_district_roads",
    name: "Major District Roads",
    category: "TRANSPORT",
    geometry_type: "MultiLineString",
    source: "/api/v1/gis/layer/major_district_roads",
    source_type: "POSTGIS",
    visibility: false,
    min_zoom: 9,
    max_zoom: 19,
    selectable: true,
    queryable: true,
    downloadable: false,
    searchable: true,
    style: { color: "#d97706", weight: 2 },
    attribution: "TNGIS Official Source",
    update_frequency: "Yearly",
    data_status: "PENDING_VERIFICATION",
    source_department: "Highways",
  },
  {
    id: "other_district_roads",
    name: "Other District Roads",
    category: "TRANSPORT",
    geometry_type: "MultiLineString",
    source: "/api/v1/gis/layer/other_district_roads",
    source_type: "POSTGIS",
    visibility: false,
    min_zoom: 10,
    max_zoom: 19,
    selectable: true,
    queryable: true,
    downloadable: false,
    searchable: true,
    style: { color: "#b45309", weight: 1.5 },
    attribution: "TNGIS Official Source",
    update_frequency: "Yearly",
    data_status: "PENDING_VERIFICATION",
    source_department: "Highways",
  },
  {
    id: "rivers",
    name: "Rivers",
    category: "WATER",
    geometry_type: "MultiLineString",
    source: "/api/v1/gis/layer/rivers",
    source_type: "POSTGIS",
    visibility: false,
    min_zoom: 6,
    max_zoom: 19,
    selectable: true,
    queryable: true,
    downloadable: false,
    searchable: true,
    style: { color: "#3b82f6", weight: 2 },
    attribution: "TNGIS Official Source",
    update_frequency: "Yearly",
    data_status: "PENDING_VERIFICATION",
    source_department: "WRD",
  },
  {
    id: "tanks",
    name: "Tanks",
    category: "WATER",
    geometry_type: "MultiPolygon",
    source: "/api/v1/gis/layer/tanks",
    source_type: "POSTGIS",
    visibility: false,
    min_zoom: 10,
    max_zoom: 19,
    selectable: true,
    queryable: true,
    downloadable: false,
    searchable: true,
    style: { color: "#60a5fa", fillColor: "#93c5fd", weight: 1, fillOpacity: 0.5 },
    attribution: "TNGIS Official Source",
    update_frequency: "Yearly",
    data_status: "PENDING_VERIFICATION",
    source_department: "WRD",
  },
  {
    id: "reservoirs",
    name: "Reservoirs",
    category: "WATER",
    geometry_type: "MultiPolygon",
    source: "/api/v1/gis/layer/reservoirs",
    source_type: "POSTGIS",
    visibility: false,
    min_zoom: 8,
    max_zoom: 19,
    selectable: true,
    queryable: true,
    downloadable: false,
    searchable: true,
    style: { color: "#2563eb", fillColor: "#3b82f6", weight: 2, fillOpacity: 0.6 },
    attribution: "TNGIS Official Source",
    update_frequency: "Yearly",
    data_status: "PENDING_VERIFICATION",
    source_department: "WRD",
  },
  {
    id: "government_offices",
    name: "Government Offices location",
    category: "GOVERNMENT_FACILITIES",
    geometry_type: "Point",
    source: "/api/v1/gis/layer/government_offices",
    source_type: "POSTGIS",
    visibility: false,
    min_zoom: 12,
    max_zoom: 19,
    selectable: true,
    queryable: true,
    downloadable: false,
    searchable: true,
    style: { icon: "🏛️" },
    attribution: "TNGIS Official Source",
    update_frequency: "Yearly",
    data_status: "PENDING_VERIFICATION",
    source_department: "Various",
  },
  {
    id: "registration_offices",
    name: "Registration Office",
    category: "GOVERNMENT_FACILITIES",
    geometry_type: "Point",
    source: "/api/v1/gis/layer/registration_offices",
    source_type: "POSTGIS",
    visibility: false,
    min_zoom: 11,
    max_zoom: 19,
    selectable: true,
    queryable: true,
    downloadable: false,
    searchable: true,
    style: { icon: "🏢" },
    attribution: "TNGIS Official Source",
    update_frequency: "Yearly",
    data_status: "PENDING_VERIFICATION",
    source_department: "Registration Department",
  },
  {
    id: "district_revenue_officers",
    name: "District Revenue Officer",
    category: "GOVERNMENT_FACILITIES",
    geometry_type: "Point",
    source: "/api/v1/gis/layer/district_revenue_officers",
    source_type: "POSTGIS",
    visibility: false,
    min_zoom: 8,
    max_zoom: 19,
    selectable: true,
    queryable: true,
    downloadable: false,
    searchable: true,
    style: { icon: "👔" },
    attribution: "TNGIS Official Source",
    update_frequency: "Yearly",
    data_status: "PENDING_VERIFICATION",
    source_department: "Revenue",
  },
  {
    id: "taluk_offices",
    name: "Taluk Office",
    category: "GOVERNMENT_FACILITIES",
    geometry_type: "Point",
    source: "/api/v1/gis/layer/taluk_offices",
    source_type: "POSTGIS",
    visibility: false,
    min_zoom: 10,
    max_zoom: 19,
    selectable: true,
    queryable: true,
    downloadable: false,
    searchable: true,
    style: { icon: "🏠" },
    attribution: "TNGIS Official Source",
    update_frequency: "Yearly",
    data_status: "PENDING_VERIFICATION",
    source_department: "Revenue",
  },
  {
    id: "village_panchayat_offices",
    name: "Village Panchayat Office",
    category: "GOVERNMENT_FACILITIES",
    geometry_type: "Point",
    source: "/api/v1/gis/layer/village_panchayat_offices",
    source_type: "POSTGIS",
    visibility: false,
    min_zoom: 12,
    max_zoom: 19,
    selectable: true,
    queryable: true,
    downloadable: false,
    searchable: true,
    style: { icon: "🏡" },
    attribution: "TNGIS Official Source",
    update_frequency: "Yearly",
    data_status: "PENDING_VERIFICATION",
    source_department: "Rural Development",
  },
  {
    id: "protected_areas",
    name: "Protected Area Sanctuaries",
    category: "FOREST",
    geometry_type: "MultiPolygon",
    source: "/api/v1/gis/layer/protected_areas",
    source_type: "POSTGIS",
    visibility: false,
    min_zoom: 6,
    max_zoom: 19,
    selectable: true,
    queryable: true,
    downloadable: false,
    searchable: true,
    style: { color: "#065f46", fillColor: "#047857", weight: 2, fillOpacity: 0.4 },
    attribution: "TNGIS Official Source",
    update_frequency: "Yearly",
    data_status: "PENDING_VERIFICATION",
    source_department: "Forest",
  },
  {
    id: "geomorphology",
    name: "Geomorphology",
    category: "NATURAL_RESOURCES",
    geometry_type: "MultiPolygon",
    source: "/api/v1/gis/layer/geomorphology",
    source_type: "POSTGIS",
    visibility: false,
    min_zoom: 6,
    max_zoom: 19,
    selectable: true,
    queryable: true,
    downloadable: false,
    searchable: true,
    style: { color: "#a16207", fillColor: "#ca8a04", weight: 1, fillOpacity: 0.3 },
    attribution: "TNGIS Official Source",
    update_frequency: "Yearly",
    data_status: "PENDING_VERIFICATION",
    source_department: "GSI",
  },
  {
    id: "railway_line",
    name: "Railway Line",
    category: "TRANSPORT",
    geometry_type: "MultiLineString",
    source: "/api/v1/gis/layer/railway_line",
    source_type: "POSTGIS",
    visibility: false,
    min_zoom: 6,
    max_zoom: 19,
    selectable: true,
    queryable: true,
    downloadable: false,
    searchable: true,
    style: { color: "#000000", weight: 2, dashArray: "5, 5" },
    attribution: "TNGIS Official Source",
    update_frequency: "Yearly",
    data_status: "PENDING_VERIFICATION",
    source_department: "Railways",
  },
  {
    id: "airport_location",
    name: "Airport Location",
    category: "TRANSPORT",
    geometry_type: "Point",
    source: "/api/v1/gis/layer/airport_location",
    source_type: "POSTGIS",
    visibility: false,
    min_zoom: 6,
    max_zoom: 19,
    selectable: true,
    queryable: true,
    downloadable: false,
    searchable: true,
    style: { icon: "✈️" },
    attribution: "TNGIS Official Source",
    update_frequency: "Yearly",
    data_status: "PENDING_VERIFICATION",
    source_department: "Airport Authority",
  },
  {
    id: "assembly_constituency",
    name: "Assembly Constituency",
    category: "ADMINISTRATIVE",
    geometry_type: "MultiPolygon",
    source: "/api/v1/gis/layer/assembly_constituency",
    source_type: "POSTGIS",
    visibility: false,
    min_zoom: 6,
    max_zoom: 19,
    selectable: true,
    queryable: true,
    downloadable: false,
    searchable: true,
    style: { color: "#be185d", fillColor: "transparent", weight: 2 },
    attribution: "TNGIS Official Source",
    update_frequency: "Yearly",
    data_status: "PENDING_VERIFICATION",
    source_department: "Election Commission",
  },
  {
    id: "parliament_constituency",
    name: "Parliament Constituency",
    category: "ADMINISTRATIVE",
    geometry_type: "MultiPolygon",
    source: "/api/v1/gis/layer/parliament_constituency",
    source_type: "POSTGIS",
    visibility: false,
    min_zoom: 5,
    max_zoom: 19,
    selectable: true,
    queryable: true,
    downloadable: false,
    searchable: true,
    style: { color: "#9d174d", fillColor: "transparent", weight: 3 },
    attribution: "TNGIS Official Source",
    update_frequency: "Yearly",
    data_status: "PENDING_VERIFICATION",
    source_department: "Election Commission",
  }
];

export const getLayersByCategory = () => {
  const categories = {} as Record<LayerCategory, LayerMetadata[]>;
    GIS_LAYER_REGISTRY.forEach((layer) => {
    if (!categories[layer.category]) {
      categories[layer.category] = [];
    }
    categories[layer.category].push(layer);
  });
  return categories;
};

export const getLayerById = (id: string) => {
  return GIS_LAYER_REGISTRY.find((l) => l.id === id);
};
